# Generated by Django 4.0.2 on 2022-04-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_ticket_completed_delete_userfollows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='completed',
            new_name='has_review',
        ),
    ]
